### PR TITLE
Adding new destination for Timeplus

### PR DESCRIPTION
**Pull request by jovezhong**
Hi @sdairs , thanks for building and opensourcing this awesome tool. I used to have a real-time twitter demo but it got too expensive and would like to get realtime social messages from bluesky.

This PR is now read-to-review. I tested it with a workspace in Timeplus Cloud, with 1360000 records. You can create a free account at https://us-west-2.timeplus.cloud, then follow the guide to create the API token: https://docs.timeplus.com/apikey. The `stream` will be created automatically if not exists. This also works with self-hosting Timeplus Enterprise, please set the token as `username:password`.

With the 5000 records in a batch, I noticed the lag can be 0 to 3 seconds, but of coz, we can load earlier messages.

A sample SQL to list the incoming posts are
```sql
SELECT 
 (record:commit.record.createdAt)::datetime64(3) as createdAt, 
 to_time(substr(record:time_us,1,13)) as time_us,
 date_diff('second',createdAt,time_us),
 record:commit.record.text as text,*
 FROM bluesky
where collection='commit' and record:commit.collection ='app.bsky.feed.post' and record:commit.operation='create'
```
image

-- original message when the PR was created.
I created the timeplus.js, basically following the tinybird.js. We also provide ingest REST API which supports JSONL. Sorry for my ignorance, I didn't figure out how to run this locally. I tried those pnpm or turbo commands based on Github action yaml but no luck. Even I cannot run those actions on my fork (I failed to build/run the web app). So I marked this PR as a draft. Please ignore the apps/cli/README.md which is generated by release action. After more tests, I will update the top level README

### CODE REVIEW

**Comment by sdairs** [comment]
Hey @jovezhong thanks for contributing! Glad its useful :) 

I updated the readme to add some steps on building + fixed some deps & build errors - I gave your PR a test and it builds fine and the command works (I didn't test against TImeplus to know if does the right thing downstream).

Probably my fault for trying to be fancy with turbo etc. 😂

**Comment by jovezhong** [comment]
Hi @sdairs , I marked this PR as read-to-review. I tested it with a workspace in Timeplus Cloud, with 1360000 records. You can create a free account at https://us-west-2.timeplus.cloud, then follow the guide to create the API token: https://docs.timeplus.com/apikey. The `stream` will be created automatically if not exists. This also works with self-hosting Timeplus Enterprise, please set the token as `username:password`.

With the 5000 records in a batch, I noticed the lag can be 0 to 3 seconds, but of coz, we can load earlier messages.

A sample SQL to list the incoming posts are
```sql
SELECT 
 (record:commit.record.createdAt)::datetime64(3) as createdAt, 
 to_time(substr(record:time_us,1,13)) as time_us,
 date_diff('second',createdAt,time_us),
 record:commit.record.text as text,*
 FROM bluesky
where collection='commit' and record:commit.collection ='app.bsky.feed.post' and record:commit.operation='create'
```
image

**Comment by sdairs** [comment]
Hey @jovezhong - tested against Timeplus cloud and works great! Going to merge

**Review by sdairs — APPROVED** [review]

**Comment by sdairs** [comment]
Added to v0.2.0 release

**Pull request merged**
